- hosts: localhost
  vars:
    nvidia_docker_gpg_key_url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    nvidia_toolkit_repository_url: "https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list"

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: no
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400 #One day
      state: present
    when: ansible_os_family == "Debian"

  - name: Update Package Manager
    become: true
    pacman:
      update_cache: true
      state: present
    when: ansible_os_family == "Archlinux"

  tasks:
    - include_tasks: tasks/setup-Debian.yml
      when: ansible_os_family == 'Debian'
      tags: [docker, nvidia-docker]
    - include_tasks: tasks/setup-Archlinux.yml
      when: ansible_os_family == "Archlinux"
      tags: [docker, nvidia-docker]

