- name: Install NVIDIA container toolkit
  become: yes
  ansible.builtin.pacman:
    name:
      - nvidia-container-toolkit
  tags: nvidia-docker

- name: Restart docker service
  become: yes
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: yes
    state: restarted
  tags: nvidia-docker
